#!/bin/bash

YOC_FOLDER=<YOC_FOLDER>
COMPOSE_FOLDER=$YOC_FOLDER/compose_files
COMPOSE_FILE=$(ls $YOC_FOLDER/compose_files/* | tr '\n' ':' | sed 's/:$//')
export COMPOSE_FILE

option=${1:-"--usage"}

usage () {
   echo "Usage: yoc --usage|restart|stop|start|update|status"
   echo "--usage     display usage message"
   echo "restart    restarts all services or a specific one"
   echo "stop       stops all services or a specific one"
   echo "start      starts services or a specific one"
   echo "update     update the containers and restart the services or a specific one"
   echo "status     display the status of the containers"
   echo " "
   echo "Exemple: yoc stop"
   echo "Exemple: yoc start seafile"
}

if [ $option == "--usage" ]; then
    usage
    exit 0
fi

if [ $option == "restart" ]; then
    if [ -z "$2" ]; then
        docker compose stop && docker compose up -d
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml stop && docker compose -f $COMPOSE_FOLDER/$2.yaml up -d
        exit 0
    fi
fi

if [ $option == "stop" ]; then
    if [ -z "$2" ]; then
        docker compose stop
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml stop
        exit 0
    fi
fi

if [ $option == "start" ]; then
    if [ -z "$2" ]; then
        docker compose up -d
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml up -d
        exit 0
    fi
fi

if [ $option == "update" ]; then
    if [ -z "$2" ]; then
        docker compose pull && docker compose up -d
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml pull && docker compose -f $COMPOSE_FOLDER/$2.yaml up -d
        exit 0
    fi
fi

if [ $option == "delete" ]; then
    if [ -z "$2" ]; then
        docker compose rm
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml rm
    fi
fi

if [ $option == "status" ]; then
    docker compose ps
    exit 0
fi