#!/bin/bash

YOC_FOLDER=<YOC_FOLDER>
COMPOSE_FOLDER=$YOC_FOLDER/compose_files
COMPOSE_FILE=$(ls $YOC_FOLDER/compose_files/* | tr '\n' ':' | sed 's/:$//')
export COMPOSE_FILE

option=${1:-"--usage"}

usage () {
   echo "Usage: yoc --usage|restart|stop|start|update|status|delete|log"
   echo "--usage     display usage message"
   echo "restart    restart the container(s)"
   echo "stop       stops the container(s)"
   echo "start      start the container(s)"
   echo "update     update the container(s)"
   echo "status     display the status of the container(s)"
   echo "delete     delete the container(s)"
   echo "log        display the logs of the container(s)"
   echo " "
   echo "Exemple: yoc stop"
   echo "Exemple: yoc start seafile"
}

if [ $option == "--usage" ]; then
    usage
    exit 0
fi

if [ $option == "restart" ]; then
    if [ -z "$2" ]; then
        docker compose stop && docker compose up -d
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml stop && docker compose -f $COMPOSE_FOLDER/$2.yaml up -d
        exit 0
    fi
fi

if [ $option == "stop" ]; then
    if [ -z "$2" ]; then
        docker compose stop
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml stop
        exit 0
    fi
fi

if [ $option == "start" ]; then
    if [ -z "$2" ]; then
        docker compose up -d
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml up -d
        exit 0
    fi
fi

if [ $option == "update" ]; then
    if [ -z "$2" ]; then
        docker compose pull && docker compose up -d
        exit 0
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml pull && docker compose -f $COMPOSE_FOLDER/$2.yaml up -d
        exit 0
    fi
fi

if [ $option == "delete" ]; then
    if [ -z "$2" ]; then
        docker compose rm
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml rm
    fi
fi

if [ $option == "log" ]; then
    if [ -z "$2" ]; then
        docker compose logs
    else
        docker compose -f $COMPOSE_FOLDER/$2.yaml logs
    fi
fi

if [ $option == "status" ]; then
    docker compose ps
    exit 0
fi