---
version: "3"
networks:
  yoc_network:
    external: true
services: 
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:latest
    volumes:
      - ${CONTAINERS_DATA}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    restart: always
    networks:
      yoc_network:
    labels:
      - traefik.http.routers.hahttp.rule=Host(`homeassistant.${DOMAIN_NAME}`)
      - traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAIN_NAME}`)
      - traefik.http.routers.homeassistant.entrypoints=web-secure
      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.homeassistant.tls.certresolver=letsencrypt