---
networks:
  yoc_network:
    external: true
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 3001
    depends_on:
      - immich_redis
      - immich_postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich-server.rule=Host(`immich.${DOMAIN_NAME}`)
      - traefik.http.routers.immich-server.entrypoints=websecure
      - traefik.http.routers.immich-server.tls.certresolver=myresolver
    restart: always
    networks:
      yoc_network:

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${CONTAINERS_DATA}/immich/model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      yoc_network:

  immich_redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    restart: always
    networks:
      yoc_network:

  immich_postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${CONTAINERS_DATA}/immich/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      yoc_network: