---
networks:
  yoc_network:
    external: true
services:
  owncloud:
    image: owncloud/server:10.15
    container_name: owncloud
    ports:
      - 8083:8080
    depends_on:
      - owncloud-mariadb
      - owncloud-redis
    environment:
      - OWNCLOUD_DOMAIN=owncloud.${DOMAIN_NAME}
      - OWNCLOUD_TRUSTED_DOMAINS=owncloud.${DOMAIN_NAME}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_DB_HOST=owncloud-mariadb
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}   
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=owncloud-redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${CONTAINERS_DATA}/owncloud/data:/mnt/data
    restart: always
    networks:
      yoc_network:
    labels:
      - traefik.http.services.owncloud.loadbalancer.server.port=8080
      - traefik.http.routers.owncloud.rule=Host(`owncloud.${DOMAIN_NAME}`)
      - traefik.http.routers.owncloud.entrypoints=websecure
      - traefik.http.routers.owncloud.tls=true
      - traefik.http.routers.owncloud.tls.certresolver=myresolver
      - traefik.http.routers.owncloud.middlewares=owncloud-headers,owncloud-dav
      - traefik.http.middlewares.owncloud-headers.headers.stsSeconds=15552000
      - traefik.http.middlewares.owncloud-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.owncloud-headers.headers.stsPreload=true
      - traefik.http.middlewares.owncloud-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.owncloud-dav.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.owncloud-dav.redirectregex.replacement=https://$$1/remote.php/dav/
      - traefik.http.middlewares.owncloud-dav.redirectregex.permanent=true

  owncloud-mariadb:
    image: mariadb:10.11 # minimum required ownCloud version is 10.9
    container_name: owncloud-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${OWNCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${OWNCLOUD_MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${CONTAINERS_DATA}/owncloud/mysql:/var/lib/mysql
    restart: always
    networks:
      yoc_network:

  owncloud-redis:
    image: redis:6
    container_name: owncloud-redis
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${CONTAINERS_DATA}/owncloud/redis:/data
    restart: always
    networks:
      yoc_network: