---
networks:
  yoc_network:
    external: true
services:
  paperless-ngx-broker:
    container_name: paperless-ngx-broker
    image: docker.io/library/redis:7
    restart: always
    volumes:
      - ${CONTAINERS_DATA}/paperless-ngx/redisdata:/data
    networks:
      yoc_network:

  paperless-ngx-db:
    container_name: paperless-ngx-db
    image: docker.io/library/mariadb:10
    restart: always
    volumes:
      - ${CONTAINERS_DATA}/paperless-ngx/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      yoc_network:

  paperless-ngx-webserver:
    container_name: paperless-ngx-webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - paperless-ngx-db
      - paperless-ngx-broker
      - paperless-ngx-gotenberg
      - paperless-ngx-tika
    ports:
      - 8000:8000
    volumes:
      - ${CONTAINERS_DATA}/paperless-ngx/data:/usr/src/paperless/data
      - ${CONTAINERS_DATA}/paperless-ngx/media:/usr/src/paperless/media
    environment:
      PAPERLESS_REDIS: redis://paperless-ngx-broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: paperless-ngx-db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: ${MARIADB_PASSWORD}
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-ngx-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-ngx-tika:9998
      PAPERLESS_URL: https://paperless-ngx.${DOMAIN_NAME}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
      PAPERLESS_ADMIN_MAIL: ${PAPERLESS_ADMIN_MAIL}
    networks:
      yoc_network:
    labels:
      - traefik.http.services.paperless-ngx-webserver.loadbalancer.server.port=8000
      - traefik.http.routers.paperless-ngx-webserver.rule=Host(`paperless-ngx.${DOMAIN_NAME}`)
      - traefik.http.routers.paperless-ngx-webserver.entrypoints=websecure
      - traefik.http.routers.paperless-ngx-webserver.tls=true
      - traefik.http.routers.paperless-ngx-webserver.tls.certresolver=myresolver

  paperless-ngx-gotenberg:
    container_name: paperless-ngx-gotenberg
    image: docker.io/gotenberg/gotenberg:7.10
    restart: always
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      yoc_network:

  paperless-ngx-tika:
    container_name: paperless-ngx-tika
    image: ghcr.io/paperless-ngx/tika:latest
    restart: always
    networks:
      yoc_network: