---
version: "3"
networks:
  yoc_network:
    external: true
services:
  db:
    image: mariadb:10.6
    container_name: seafile-db
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_MYSQL_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${CONTAINERS_DATA}/seafile/db:/var/lib/mysql
    restart: always
    networks:
      yoc_network:

  memcached:
    image: memcached:1.6.18
    container_name: memcached
    entrypoint: memcached -m 256
    restart: always
    networks:
      yoc_network:

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - 8081:80
    volumes:
      - ${CONTAINERS_DATA}/seafile/shared:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=${SEAFILE_MYSQL_PASSWORD}
      - SEAFILE_ADMIN_EMAIL=${EMAIL_ADDRESS}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=seafile.${DOMAIN_NAME}
    depends_on:
      - db
      - memcached
    restart: always
    networks:
      yoc_network:
    labels:
      - traefik.http.routers.seafile.rule=Host(`seafile.${DOMAIN_NAME}`)
      - traefik.http.routers.seafile.entrypoints=web-secure
      - traefik.http.routers.seafile.tls=true
      - traefik.http.routers.seafile.tls.certresolver=letsencrypt