---
networks:
  yoc_network:
    external: true
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://vaultwarden.${DOMAIN_NAME}
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=${PUSH_INSTALLATION_ID}
      - PUSH_INSTALLATION_KEY=${PUSH_INSTALLATION_KEY}
      - PUSH_RELAY_BASE_URI=https://push.bitwarden.com
    volumes:
      - ${CONTAINERS_DATA}/vaultwarden:/data
    ports:
      - 80
    restart: always
    networks:
      yoc_network:
    labels:
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.${DOMAIN_NAME}`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt