---
networks:
  yoc_network:
    external: true
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      PASSWORD_HASH: ${WG_EASY_PASSWORD_HASH}
      WG_HOST: vpn.${DOMAIN_NAME}
      WG_PORT: 51820
      WG_DEFAULT_DNS: ${WG_DEFAULT_DNS}
    volumes:
      - ${CONTAINERS_DATA}/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      yoc_network: